name       : liblo
version    : '0.30'
release    : 3
source     :
    - https://github.com/radarsat1/liblo/archive/0.30.tar.gz : d8d2207acc6c282751cc2bbe97a3f84279e1ab0fc5807e3e904bc39fd8e1b3e5
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Lightweight Open Sound Control (OSC) implementation
description: |
    A lightweight library to handle the receiving and sending of messages according to the Open Sound Control (OSC) protocol.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
