name       : liblo
version    : 0.28
release    : 1
source     :
    - https://github.com/radarsat1/liblo/archive/0.28.tar.gz : 10434d05b462402d6d9976c797e073fbb98635e10f1a37a2804eee45e3414ada
license    : LGPL-2.1
component  : multimedia.library
summary    : Lightweight Open Sound Control (OSC) implementation
description: |
    A lightweight library to handle the receiving and sending of messages according to the Open Sound Control (OSC) protocol.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
