name       : liblo
version    : '0.31'
release    : 4
source     :
    - https://github.com/radarsat1/liblo/archive/0.31.tar.gz : 71d1819bcd18be66bd80c95a2d3159b9ca6f13746ddbaf1e489128f3bf46d231
homepage   : https://github.com/radarsat1/liblo
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Lightweight Open Sound Control (OSC) implementation
description: |
    A lightweight library to handle the receiving and sending of messages according to the Open Sound Control (OSC) protocol.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
