name        : liblo
version     : 0.28
release     : 1
source      :
    - https://dl.dropboxusercontent.com/u/55730378/pkgsrc/lib/liblo-0.28.tar.gz : da94a9b67b93625354dd89ff7fe31e5297fc9400b6eaf7378c82ee1caf7db909
license     :
    - LGPL-2.0
component   : multimedia.library
summary     : Lightweight Open Sound Control (OSC) implementation
description : |
    A lightweight library to handle the receiving and sending of messages according to the Open Sound Control (OSC) protocol.
setup       : |
    %reconfigure
build       : |
    %make
install     : |
    %make_install
